language: go
install: go get -v github.com/spf13/hugo
script:
  - hugo
  - python --version
  - sudo pip install s3cmd awscli
  - s3cmd sync --delete-removed -P -M -r public/ s3://mariage-s-et-r.fr/
  - mkdir ~/.aws
  - echo "[preview]" > ~/.aws/config
  - echo "cloudfront = true" >> ~/.aws/config
  - echo "[default]" > ~/.aws/credentials
  - echo "aws_access_key_id=${AWS_ACCESS_KEY}" > ~/.aws/credentials
  - echo "aws_secret_access_key=${AWS_SECRET_KEY}" >> ~/.aws/credentials
  - aws cloudfront create-invalidation --distribution-id E13N12K0DVITI9 --paths "/*"
notifications:
    email:
        on_failure: always
