language: go
install: go get -v github.com/spf13/hugo
script:
  - hugo
  - python --version
  - sudo pip install s3cmd awscli
  - s3cmd sync --delete-removed -P -M -r public/ s3://mariage-s-et-r.fr/
  - aws cloudfront create-invalidation --distribution-id E13N12K0DVITI9 --paths "/*"
notifications:
    email:
        on_failure: always
