title = "Mariage S&R"
baseURL = "https://mariage-s-et-r.fr"
tags = ["portfolio", "wedding", "blog", "mariage"]
languageCode = "fr-FR"
config = "config.toml"
theme = "osprey2"
#canonifyURLS = true
googleAnalytics = "UA-102642914-1"
disqusShortname = "mariage-s-r"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies
uglyurls = true

[Params]
    tagline = "Mariage S&R"
    author = "Ségolène et Raphaël"
    description = "Nous nous marions et sommes impatients d'y être"
    logoBig = "/images/initiales_filigrane.png"
    logoSmall = "/images/initiales_filigrane.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/initiales_filigrane.png"
    twitter = ""
    linkedin = ""
    github = ""
    email = ""
    googleTagManager = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = true
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true
    googleMapsAPIKey = "AIzaSyCfpRkrg1lIKKgsFC5zJnzBspE8a6Ee2Rg"

[permalinks]
    gallery = "/" # Redirect gallery index to home page

[[menu.main]]
    name = "Nous"
    url  = "/#about"
    weight = 1
#[[menu.main]]
#    name = "Blog"
#    url  = "/#blog"
#    weight = 2
[[menu.main]]
    name = "Galerie"
    url  = "/#gallery"
    weight = 3
[[menu.main]]
    name = "Logistique"
    url  = "/#logistique"
    weight = 4
[[menu.main]]
    name = "Discutons"
    url  = "/#contact"
    weight = 5
